import{a as h,S as g,i as a}from"./assets/vendor-BSTwZ_tR.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&o(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const y="52852396-2e2f44ee304cf9c0c54250cb9",b="https://pixabay.com/api/";function L(t){return h.get(b,{params:{key:y,q:t.trim(),image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40}}).then(i=>i.data)}const f=document.getElementById("gallery"),l=document.getElementById("loader");let c=null;function A(){return c||(c=new g(".gallery a",{captions:!0,captionsData:"alt",captionDelay:200,animationSpeed:180,overlayOpacity:.9})),c}function v(t){if(!Array.isArray(t)||t.length===0)return;const i=t.map(({webformatURL:n="",largeImageURL:o="#",tags:e="",likes:r=0,views:s=0,comments:d=0,downloads:m=0})=>`
      <li class="card">
      <a href="${o}">
        <img src="${n}" alt="${I(e)}" loading="lazy"/>
      </a>
      <div class="meta">
        <span>❤ Likes: <b>${r}</b></span>
        <span>👁 Views: <b>${s}</b></span>
        <span>💬 Comments: <b>${d}</b></span>
        <span>⬇ Downloads: <b>${m}</b></span>
      </div>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",i),A().refresh()}function E(){f.innerHTML=""}function S(){l.classList.remove("is-hidden"),l.setAttribute("aria-hidden","false")}function $(){l.classList.add("is-hidden"),l.setAttribute("aria-hidden","true")}function I(t=""){return String(t).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;")}const u=document.getElementById("search-form"),O=u.querySelector('button[type="submit"]');u.addEventListener("submit",P);function P(t){t.preventDefault();const i=u.elements["search-text"].value.trim();if(!i){a.warning({title:"Упс",message:"Введи ключове слово перед пошуком.",position:"topRight"});return}E(),p(!0),L(i).then(n=>{const o=(n==null?void 0:n.hits)??[];if(o.length===0){a.info({title:"Нічого не знайдено",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}v(o),a.success({title:"Готово",message:`Знайдено: ${n.totalHits}. Показано: ${o.length}.`,position:"topRight",timeout:2200})}).catch(()=>{a.error({title:"Помилка",message:"Проблема з мережею або API. Спробуй пізніше.",position:"topRight"})}).finally(()=>p(!1))}function p(t){O.disabled=t,t?S():$()}
//# sourceMappingURL=index.js.map
