import{a as h,S as g,i as a}from"./assets/vendor-BSTwZ_tR.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&o(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const y="52852396-2e2f44ee304cf9c0c54250cb9",b="https://pixabay.com/api/";function L(r){return h.get(b,{params:{key:y,q:r.trim(),image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40}}).then(i=>i.data)}const d=document.getElementById("gallery"),c=document.getElementById("loader");let l=null;function v(){return l||(l=new g(".gallery a",{captions:!0,captionsData:"alt",captionDelay:200,animationSpeed:180,overlayOpacity:.9})),l}function A(r){if(!Array.isArray(r)||r.length===0)return;const i=r.map(({webformatURL:n="",largeImageURL:o="#",tags:e="",likes:t=0,views:s=0,comments:p=0,downloads:m=0})=>`
      <li class="card">
      <a href="${o}">
        <img src="${n}" alt="${e}" loading="lazy"/>
      </a>
      <div class="meta">
        <span>❤ Likes: <b>${t}</b></span>
        <span>👁 Views: <b>${s}</b></span>
        <span>💬 Comments: <b>${p}</b></span>
        <span>⬇ Downloads: <b>${m}</b></span>
      </div>
    </li>
  `).join("");d.insertAdjacentHTML("beforeend",i),v().refresh()}function E(){d.innerHTML=""}function $(){c.classList.remove("is-hidden"),c.setAttribute("aria-hidden","false")}function S(){c.classList.add("is-hidden"),c.setAttribute("aria-hidden","true")}const u=document.getElementById("search-form"),I=u.querySelector('button[type="submit"]');u.addEventListener("submit",O);function O(r){r.preventDefault();const i=u.elements["search-text"].value.trim();if(!i){a.warning({title:"Упс",message:"Введи ключове слово перед пошуком.",position:"topRight"});return}E(),f(!0),L(i).then(n=>{const o=(n==null?void 0:n.hits)??[];if(o.length===0){a.info({title:"Нічого не знайдено",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}A(o),a.success({title:"Готово",message:`Знайдено: ${n.totalHits}. Показано: ${o.length}.`,position:"topRight",timeout:2200})}).catch(()=>{a.error({title:"Помилка",message:"Проблема з мережею або API. Спробуй пізніше.",position:"topRight"})}).finally(()=>f(!1))}function f(r){I.disabled=r,r?$():S()}
//# sourceMappingURL=index.js.map
